# Generated by Django 3.2 on 2021-06-02 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('authorImage', models.ImageField(upload_to='Author')),
                ('authorExp', models.CharField(max_length=100)),
                ('shortDesc', models.TextField(max_length=300)),
            ],
        ),
    ]
