# Generated by Django 3.2 on 2021-06-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210602_2356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-pk']},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='read',
            field=models.IntegerField(default=0),
        ),
    ]
